#!/bin/bash

RASPBERRYS=( rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 )
if [ $# -gt 0 ];
then
RASPBERRYS=() 
for par in ¨$@¨
do
RASPBERRYS+=($par)
done
fi
for i in ¨${RASPBERRYS[@]}¨
do
   ping -c 1 -W 1 $i &>/dev/null
if [ $? -eq 1 ];
then 
echo $i off
else
echo $i on
fi
done
